package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;
    public static final int blockMemory = 131072;

    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    private JoinPredicate p;
    private DbIterator child1, child2;
    private TupleIterator join_res;
    private TupleDesc merged_tupledesc;
    public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
        this.p=p;
        this.child1=child1;
        this.child2=child2;
        merged_tupledesc=TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());
    }

    public JoinPredicate getJoinPredicate() {
        // some code goes here
        return p;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        // some code goes here
        return child1.getTupleDesc().getFieldName(p.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        // some code goes here
        return child2.getTupleDesc().getFieldName(p.getField2());
    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // some code goes here
        return TupleDesc.merge(child1.getTupleDesc(),child2.getTupleDesc());
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // some code goes here
        super.open();
        child1.open(); child2.open();
        join_res=nestedLoopJoin();
        join_res.open();
    }

    public void close() {
        // some code goes here
        super.close();
        child1.close(); child2.close();
        join_res.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // some code goes here
        child1.rewind(); child2.rewind();
        join_res.rewind();
    }
    private Tuple merge_tuples(Tuple t1, Tuple t2){
        Tuple res= new Tuple(merged_tupledesc);
        int l1=t1.getTupleDesc().numFields();
        int l2=t2.getTupleDesc().numFields();
        for (int i=0;i<l1;++i){
            res.setField(i, t1.getField(i));
        }
        for (int j=0;j<l2;++j){
            res.setField(j+l1, t2.getField(j));
        }
        return res;
    }
    private TupleIterator nestedLoopJoin() throws DbException, TransactionAbortedException{
        LinkedList<Tuple> tuples = new LinkedList<>();
        child1.rewind();
        while (child1.hasNext()){
            Tuple t1=child1.next();
            child2.rewind();
            while(child2.hasNext()){
                Tuple t2=child2.next();
                if(p.filter(t1,t2)){
                    tuples.add(merge_tuples(t1,t2));
                }
            }
        }
        return new TupleIterator(merged_tupledesc, tuples);
    }
    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // some code goes here
        if(join_res.hasNext()){
            return join_res.next();
        }
        return null;
    }

    @Override
    public DbIterator[] getChildren() {
        // some code goes here
        return new DbIterator[]{ child1, child2};
    }

    @Override
    public void setChildren(DbIterator[] children) {
        // some code goes here
        child1=children[0];
        child2=children[1];
    }

}
